[package]
name = "tct"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
lazy_static = "1.4.0"
memmap2 = "0.5.8"
rustc-hash = "1.1.0"

[profile.release]
lto = "fat"
codegen-units = 1
